Extension point to provide data source information.
saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.DS pull request #3
Opened 2017-06-29 15:05 UTC by irium

Added extension point to provide data source information by user-provided class.

Existing solution with assembly-level attributes is static, but sometimes it needs to be read from some external source (config file, registry etc).

Example usage:
```
public class AppInfo : IDataSourceInfo
{
        public Version Version { get; } = new Version();
        public string Company { get; }
        public string ProductFamily { get; }
        public string ProductName { get; }

        public AppInfo()
        {
            // Somehow read data source information...
        }
    }
}

[DataSourceInfoProvider(typeof(AppInfo))]
public sealed class MyCoolBitmapDataSource : BitmapDataSource, IDisposable
{
    ...
}
```

2017-06-29 19:01 UTC, saraff-9EB1047A4BEB4cef8506B29BA325BD5A requested changes
Please, make required changes to the code.

2017-06-29 19:01 UTC, saraff-9EB1047A4BEB4cef8506B29BA325BD5A commented on DataSourceInfoProviderAttribute.cs
> +{
Code formatting should be the same as in the whole project (including brackets, variable names, indents, etc.)

2017-06-29 19:01 UTC, saraff-9EB1047A4BEB4cef8506B29BA325BD5A commented on DataSourceInfoProviderAttribute.cs
> +    public interface IDataSourceInfo
Why need a interface? Why we can not use only a DataSourceInfo class?

2017-06-29 19:01 UTC, saraff-9EB1047A4BEB4cef8506B29BA325BD5A commented on DataSourceInfoProviderAttribute.cs
> +        public Type Type { get; }
Code structure should be the same as in the whole project (A properties must be after a constructors).

2017-06-29 19:01 UTC, saraff-9EB1047A4BEB4cef8506B29BA325BD5A commented on DataSourceServices.cs
> +            var asm = HandlerType.Assembly;
Code formatting should be the same as in the whole project (including brackets, variable names, indents, etc.)
Refactoring existing variables unacceptable.
Using the "this" keyword for instance items (as field, properties and methods) is mandatory

2017-06-29 19:01 UTC, saraff-9EB1047A4BEB4cef8506B29BA325BD5A commented on DataSourceServices.cs
> +            IDataSourceInfo custom = new DataSourceInfo();
Why you create instance that never use?

2017-06-29 19:01 UTC, saraff-9EB1047A4BEB4cef8506B29BA325BD5A commented on DataSourceInfoProviderAttribute.cs
> +    {
Maybe better define one method (DataSourceInfo GetDataSourceInfo() as sample) instead four.

2017-06-29 19:01 UTC, saraff-9EB1047A4BEB4cef8506B29BA325BD5A commented on DataSourceServices.cs
> +                custom = Activator.CreateInstance(provider.Type) as IDataSourceInfo ?? new DataSourceInfo();
I think that code for creating a provider must be moved to property (to a getter).
If custom provide don't exist that need use default provider (but is not empty provider).

2017-07-07 23:17 UTC, saraff-9EB1047A4BEB4cef8506B29BA325BD5A commented
Extension point to provide data source identity implemented as follow (see [commit 872eab88981b431dd5a56617083afc120d4efc97](https://github.com/saraff-9EB1047A4BEB4cef8506B29BA325BD5A/Saraff.Twain.DS/commit/872eab88981b431dd5a56617083afc120d4efc97)).
```C#
[assembly: DataSource(
    typeof(Saraff.Twain.DS.Screen.ScreenDataSource),
    Country = TwCountry.BELARUS,
    Language = TwLanguage.RUSSIAN,
    MaxConnectionCount = 64,
    IdentityProvider = typeof(_IdentityProvider))]

internal sealed class _IdentityProvider:IIdentityProvider {

    public Identity Identity {
        get {
            return new Identity {
                Company="asdf",
                ProductFamily="zcvx",
                ProductName="wert",
                Version=new Version(4,5)
            };
        }
    }
}
```

2017-07-07 23:17 UTC, closed without merging

2017-07-08 17:35 UTC, irium commented
Thanks!